const STORAGE_KEY='roasteryProducts';
const defaults=[
{id:1,name:'Etiyopya Guji Filtre Kahve 250 g',brand:'KARAHANLI',price:495,oldPrice:550,category:'gida',badge:'Yeni',color:'#72462f',stock:24,image:''},{id:2,name:'Brezilya Cerrado Espresso 1 kg',brand:'KARAHANLI',price:1190,oldPrice:1320,category:'gida',badge:'%10',color:'#3f2c24',stock:18,image:''},{id:3,name:'Compact Pro Espresso Makinesi',brand:'NOVA',price:28990,oldPrice:null,category:'ekipman',badge:'Çok Satan',color:'#444444',stock:6,image:''},{id:4,name:'Elektrikli Kahve Değirmeni',brand:'MAZZ',price:8990,oldPrice:9750,category:'ekipman',badge:'Fırsat',color:'#444444',stock:9,image:''},{id:5,name:'Kolombiya Huila Filtre Kahve 250 g',brand:'KARAHANLI',price:475,oldPrice:null,category:'gida',badge:null,color:'#9a694d',stock:32,image:''},{id:6,name:'Dual Boiler Espresso Makinesi',brand:'LINEA',price:76900,oldPrice:null,category:'ekipman',badge:'Profesyonel',color:'#444444',stock:3,image:''},{id:7,name:'Hassas Barista Terazisi',brand:'FELLOW',price:2590,oldPrice:2890,category:'ekipman',badge:'%10',color:'#444444',stock:14,image:''},{id:8,name:'Paslanmaz Çelik Süt Potu 600 ml',brand:'BARISTA',price:890,oldPrice:null,category:'ekipman',badge:null,color:'#444444',stock:20,image:''},{id:9,name:'Mutfak Planlama ve Yerinde Keşif Hizmeti',brand:'KARAHANLI',price:1500,oldPrice:null,category:'hizmet',badge:'Popüler',color:'#28392f',stock:99,image:''}];
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(p)?p:defaults}catch{return defaults}}let products=load();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(products));render()}
const labels={gida:'Gıda',ekipman:'Ekipman',hizmet:'Hizmet'};
function render(){const q=$('adminSearch').value.toLocaleLowerCase('tr-TR'),filter=$('categoryFilter').value;const list=products.filter(p=>(filter==='all'||p.category===filter)&&(`${p.name} ${p.brand}`).toLocaleLowerCase('tr-TR').includes(q));$('productCount').textContent=`${products.length} kayıt`;$('stats').innerHTML=`<article class="stat"><span>Toplam ürün</span><strong>${products.length}</strong></article><article class="stat"><span>Toplam stok</span><strong>${products.reduce((s,p)=>s+Number(p.stock||0),0)}</strong></article><article class="stat"><span>Stokta olmayan</span><strong>${products.filter(p=>Number(p.stock)<=0).length}</strong></article><article class="stat"><span>Ortalama fiyat</span><strong>${money(products.length?products.reduce((s,p)=>s+Number(p.price),0)/products.length:0)}</strong></article>`;$('productTable').innerHTML=list.length?list.map(p=>`<tr><td><div class="product-cell"><div class="thumb" style="${p.image?`background-image:url('${esc(p.image)}')`:`background:${esc(p.color||'#555')}`}">${p.image?'':esc((p.brand||'?')[0])}</div><div><strong>${esc(p.name)}</strong><small>${esc(p.brand)}</small></div></div></td><td><span class="category-pill">${labels[p.category]||esc(p.category)}</span></td><td><strong>${money(p.price)}</strong>${p.oldPrice?`<br><small><del>${money(p.oldPrice)}</del></small>`:''}</td><td><span class="stock-pill ${Number(p.stock)<=0?'out':Number(p.stock)<5?'low':''}">${Number(p.stock)||0}</span></td><td>${esc(p.badge||'—')}</td><td><div class="row-actions"><button class="icon-action" data-edit="${p.id}">Düzenle</button><button class="icon-action delete" data-delete="${p.id}">Sil</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">Eşleşen ürün bulunamadı.</td></tr>'}
function openModal(product){$('productForm').reset();$('productId').value=product?.id||'';$('modalTitle').textContent=product?'Ürünü Düzenle':'Yeni Ürün';$('name').value=product?.name||'';$('brand').value=product?.brand||'';$('category').value=product?.category||'gida';$('price').value=product?.price??'';$('oldPrice').value=product?.oldPrice??'';$('stock').value=product?.stock??0;$('badge').value=product?.badge||'';$('color').value=product?.color||'#72462f';$('image').value=product?.image||'';$('modalBackdrop').hidden=false;$('name').focus()}
function closeModal(){$('modalBackdrop').hidden=true}
$('newProductBtn').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('cancelBtn').onclick=closeModal;$('modalBackdrop').addEventListener('click',e=>{if(e.target===$('modalBackdrop'))closeModal()});
$('productForm').addEventListener('submit',e=>{e.preventDefault();const id=Number($('productId').value);const item={id:id||Date.now(),name:$('name').value.trim(),brand:$('brand').value.trim(),category:$('category').value,price:Number($('price').value),oldPrice:$('oldPrice').value?Number($('oldPrice').value):null,stock:Number($('stock').value),badge:$('badge').value.trim()||null,color:$('color').value,image:$('image').value.trim()};if(item.oldPrice!==null&&item.oldPrice<item.price){showToast('Eski fiyat satış fiyatından düşük olamaz');return}if(id){products=products.map(p=>p.id===id?item:p);showToast('Ürün güncellendi')}else{products.unshift(item);showToast('Ürün eklendi')}save();closeModal()});
$('productTable').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openModal(products.find(p=>p.id===Number(edit.dataset.edit)));if(del){const p=products.find(x=>x.id===Number(del.dataset.delete));if(confirm(`“${p.name}” ürünü silinsin mi?`)){products=products.filter(x=>x.id!==p.id);save();showToast('Ürün silindi')}}});
$('adminSearch').addEventListener('input',render);$('categoryFilter').addEventListener('change',render);
$('resetBtn').onclick=()=>{if(confirm('Tüm değişiklikler silinip varsayılan ürünlere dönülsün mü?')){products=structuredClone(defaults);save();showToast('Varsayılan ürünler yüklendi')}};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='roastery-products.json';a.click();URL.revokeObjectURL(a.href)};
$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data))throw new Error();products=data.map((p,i)=>({...p,id:Number(p.id)||Date.now()+i,price:Number(p.price)||0,stock:Number(p.stock)||0}));save();showToast('Ürün dosyası yüklendi')}catch{alert('Geçersiz JSON dosyası.')}e.target.value=''});
function showToast(msg){const t=$('adminToast');t.textContent=msg;t.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>t.classList.remove('show'),1700)}render();

// Handle Admin Logout
if ($('logoutBtn')) {
  $('logoutBtn').onclick = (e) => {
    e.preventDefault();
    if (confirm('Çıkış yapmak istediğinize emin misiniz?')) {
      localStorage.removeItem('karahanliUser');
      location.href = 'index.html';
    }
  };
}
